"""okf_wiki — OKF v0.2 knowledge-bundle CLI.

Core is stdlib-only; optional extras (ast/graph/server) add third-party deps.
The .skills/ markdown instructions remain the source of truth for behavior;
this package mirrors their invariants (parity is enforced by tests/CI).
"""

try:  # generated by hatch-vcs at build time; absent on raw-tree runs
    from okf_wiki._version import __version__
except ImportError:  # pragma: no cover
    __version__ = "0.0.0.dev0"

__all__ = ["__version__"]
